export const FETCH_HOME_ITEMS_LIST_REQUEST = "FETCH_HOME_ITEMS_LIST_REQUEST";
export const FETCH_HOME_ITEMS_LIST_SUCCESS = "FETCH_HOME_ITEMS_LIST_SUCCESS";
export const FETCH_HOME_ITEMS_LIST_FAILURE = "FETCH_HOME_ITEMS_LIST_FAILURE";
export const CHANGE_ACTIVE_HOME_ITEM = "CHANGE_ACTIVE_HOME_ITEM";
export const CHANGE_INFO_TO_HOME_ITEM = "CHANGE_INFO_TO_HOME_ITEM";
